version: "3"

services:
  nginx:
    image: nginx:1.17
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm


  php-fpm:
    build: ./.docker/php-fpm/
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
