version: "3"

services:
  nginx:
    image: nginx:1.17
    working_dir: /var/www/app
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - wordpress


  php-fpm:
    build: ./.docker/php-fpm/
    working_dir: /var/www/app
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql
    environment:
      PHP_IDE_CONFIG: serverName=Wordpress
      XDEBUG_CONFIG: remote_host=192.168.220.1
      PROJECT_ROOT: /var/www/app
      WEB_ROOT: /var/www/app/public
    user: "1000:1000"
    networks:
      - wordpress


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
